#version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    #platform: linux/amd64
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    image: maksimkata123/flask_app:latest
    build:
      context: .
      dockerfile: Dockerfile
      #platform: linux/amd64
      #args:
      #  - TARGETARCH=amd64
    container_name: flask_app
    restart: always
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/exercise-1
    depends_on:
      - mongodb

volumes:
  mongo_data: