services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  app:
    image: maksimkata123/flask_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/exercise-1
    depends_on:
      - mongodb
volumes:
  mongo_data: